export const LOADED_CSV = 'LOADED_CSV';

// inputs
export const SWORDMASTER_CHANGED      = 'SWORDMASTER_CHANGED';
export const HERO_LEVEL_CHANGED       = 'HERO_LEVEL_CHANGED';
export const HERO_WEAPON_CHANGED      = 'HERO_WEAPON_CHANGED';
export const ARTIFACT_LEVEL_CHANGED   = 'ARTIFACT_LEVEL_CHANGED';
export const PET_LEVEL_CHANGED        = 'PET_LEVEL_CHANGED';
export const PET_ACTIVE_CHANGED       = 'PET_ACTIVE_CHANGED';
export const EQUIPMENT_LEVEL_CHANGED  = 'EQUIPMENT_LEVEL_CHANGED';
export const EQUIPMENT_BONUS_CHANGED  = 'EQUIPMENT_BONUS_CHANGED';
export const EQUIPMENT_ACTIVE_CHANGED = 'EQUIPMENT_ACTIVE_CHANGED';
export const SKILL_LEVEL_CHANGED      = "SKILL_LEVEL_CHANGED";

export const STEPS_REQUESTED = "STEPS_REQUESTED";
export const STEPS_CHANGED   = "STEPS_CHANGED";
export const STEP_APPLIED = "STEP_APPLIED";
export const SUMMARY_STEP_APPLIED = "SUMMARY_STEP_APPLIED";
export const ALL_STEPS_APPLIED = "ALL_STEPS_APPLIED";
export const RESET_STEPS = "RESET_STEPS";

export const METHOD_CHANGED = "METHOD_CHANGED";
export const AORDER_CHANGED = "AORDER_CHANGED";
export const TOGGLE_ADVANCED = "TOGGLE_ADVANCED";
export const TOGGLE_UPDATE = "TOGGLE_UPDATE";

export const OPTION_VALUE_CHANGED = "OPTION_VALUE_CHANGED";
export const EQUIPMENT_ADDED      = 'EQUIPMENT_ADDED';
export const EQUIPMENT_REMOVED    = 'EQUIPMENT_REMOVED';
export const EQUIPMENT_SELECTED   = 'EQUIPMENT_SELECTED';
export const EQUIPMENT_ADDED_BONUS = 'EQUIPMENT_ADDED_BONUS';

export const USERNAME_CHANGED = "USERNAME_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const TOKEN_CHANGED = "TOKEN_CHANGED";
export const LOGOUT = 'LOGOUT';

export const NEW_GAME_STATE = "NEW_GAME_STATE";
export const STATE_FROM_SERVER = "STATE_FROM_SERVER";
// options

// UI
export const TAB_CHANGED = "TAB_CHANGED";

export const TEST = 'TEST';