export const LOADED_CSV = 'LOADED_CSV';

// inputs
export const SWORDMASTER_CHANGED      = 'SWORDMASTER_CHANGED';
export const HERO_LEVEL_CHANGED       = 'HERO_LEVEL_CHANGED';
export const HERO_WEAPON_CHANGED      = 'HERO_WEAPON_CHANGED';
export const ARTIFACT_LEVEL_CHANGED   = 'ARTIFACT_LEVEL_CHANGED';
export const PET_LEVEL_CHANGED        = 'PET_LEVEL_CHANGED';
export const PET_ACTIVE_CHANGED       = 'PET_ACTIVE_CHANGED';
export const EQUIPMENT_LEVEL_CHANGED  = 'EQUIPMENT_LEVEL_CHANGED';
export const EQUIPMENT_ACTIVE_CHANGED = 'EQUIPMENT_ACTIVE_CHANGED';
export const SKILL_LEVEL_CHANGED      = "SKILL_LEVEL_CHANGED";

export const STEPS_CHANGED = "STEPS_CHANGED";

export const NEW_GAME_STATE = "NEW_GAME_STATE";
// options

// UI

export const TEST = 'TEST';