export const BonusType = {
  AllDamage                :  0,
  AllHelperDamage          :  1,
  MeleeHelperDamage        :  2,
  RangedHelperDamage       :  3,
  SpellHelperDamage        :  4,
  CritDamage               :  5,
  ArmorBoost               :  6,
  ArtifactDamage           :  7,
  AuraBoost                :  8,
  BossTimer                :  9,
  BurstDamageSkillAmount   : 10,
  BurstDamageSkillMana     : 11,
  ChestAmount              : 12,
  ChestChance              : 13,
  ClanQTEDamage            : 14,
  CritBoostSkillDuration   : 15,
  CritBoostSkillAmount     : 16,
  CritBoostSkillMana       : 17,
  CritChance               : 18,
  DoubleFairyChance        : 19,
  GoblinQTE                : 20,
  GoldAll                  : 21,
  GoldBoss                 : 22,
  GoldMonster              : 23,
  Goldx10Chance            : 24,
  HandOfMidasSkillDuration : 25,
  HandOfMidasSkillAmount   : 26,
  HandOfMidasSkillMana     : 27,
  HelmetBoost              : 28,
  HelperBoostSkillDuration : 29,
  HelperBoostSkillAmount   : 30,
  HelperBoostSkillMana     : 31,
  HelperUpgradeCost        : 32,
  HelperQTECount           : 33,
  InactiveAdvance          : 34,
  InactiveGold             : 35,
  ManaPoolCap              : 36,
  ManaRegen                : 37,
  ManaMonsterMana          : 38,
  ManaTapRegen             : 39,
  ThisHelperDamage         : 40,
  Memory                   : 41,
  MonsterCountPerStage     : 42,
  MonsterHP                : 43,
  PetDamage                : 44,
  PetDamageMult            : 45,
  PetBossDamage            : 46,
  PetBossCount             : 47,
  PetQTEGold               : 48,
  PetOfflineDamage         : 49,
  PrestigeRelic            : 50,
  ShadowCloneSkillDuration : 51,
  ShadowCloneSkillAmount   : 52,
  ShadowCloneSkillMana     : 53,
  SplashDamage             : 54,
  SlashBoost               : 55,
  SwordBoost               : 56,
  TapBoostSkillDuration    : 57,
  TapBoostSkillAmount      : 58,
  TapBoostSkillMana        : 59,
  TapDamage                : 60,
  TapDamageFromHelpers     : 61,
};

export const additiveBonuses = {
  [BonusType.ArtifactDamage           ]: true,
  [BonusType.BossTimer                ]: true,
  [BonusType.BurstDamageSkillMana     ]: true,
  [BonusType.ChestChance              ]: true,
  [BonusType.CritBoostSkillDuration   ]: true,
  [BonusType.CritBoostSkillMana       ]: true,
  [BonusType.CritChance               ]: true,
  [BonusType.DoubleFairyChance        ]: true,
  [BonusType.Goldx10Chance            ]: true,
  [BonusType.HandOfMidasSkillDuration ]: true,
  [BonusType.HandOfMidasSkillMana     ]: true,
  [BonusType.HelperBoostSkillDuration ]: true,
  [BonusType.HelperBoostSkillMana     ]: true,
  [BonusType.HelperUpgradeCost        ]: true,
  [BonusType.HelperQTECount           ]: true,
  [BonusType.InactiveAdvance          ]: true,
  [BonusType.ManaPoolCap              ]: true,
  [BonusType.ManaRegen                ]: true,
  [BonusType.ManaMonsterMana          ]: true,
  [BonusType.ManaTapRegen             ]: true,
  [BonusType.Memory                   ]: true,
  [BonusType.MonsterCountPerStage     ]: true,
  [BonusType.PetDamage                ]: true,
  [BonusType.PetBossCount             ]: true,
  [BonusType.PetQTEGold               ]: true,
  [BonusType.PetOfflineDamage         ]: true,
  [BonusType.ShadowCloneSkillDuration ]: true,
  [BonusType.ShadowCloneSkillMana     ]: true,
  [BonusType.SplashDamage             ]: true,
  [BonusType.TapBoostSkillDuration    ]: true,
  [BonusType.TapBoostSkillMana        ]: true,
  [BonusType.TapDamageFromHelpers     ]: true,
};

export function addBonus(allBonuses, bonusType, magnitude) {
  if (bonusType in allBonuses) {
    if (bonusType in additiveBonuses) {
      allBonuses[bonusType] += magnitude;
    } else {
      allBonuses[bonusType] *= magnitude;
    }
  } else {
    allBonuses[bonusType] = magnitude;
  }
}
